# =============================================================================
# Docker Compose Production Configuration for Starseed Node
# =============================================================================
# Run with: docker-compose -f docker-compose.production.yml up -d
# =============================================================================

version: '3.8'

services:
  # Starseed Node Application
  starseed-node:
    build: .
    container_name: starseed-node
    restart: unless-stopped
    ports:
      - "127.0.0.1:30437:30437"
    environment:
      - NODE_ENV=production
      - DEPLOYMENT_TYPE=direct
      - HOST=0.0.0.0
      - PORT=30437
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - mongodb
      - postgresql
      - weaviate
      - neo4j
    networks:
      - starseed-network

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: starseed-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=your-secure-password
      - MONGO_INITDB_DATABASE=starseed_prod
    volumes:
      - mongodb_data:/data/db
      - ./deployment/mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - starseed-network

  # PostgreSQL Database
  postgresql:
    image: postgres:15
    container_name: starseed-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=starseed_prod
      - POSTGRES_USER=starseed_user
      - POSTGRES_PASSWORD=your-secure-password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./deployment/postgresql/init:/docker-entrypoint-initdb.d
    networks:
      - starseed-network

  # Weaviate Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.22.4
    container_name: starseed-weaviate
    restart: unless-stopped
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - ENABLE_MODULES=text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - starseed-network

  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.15
    container_name: starseed-neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/your-secure-password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - starseed-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: starseed-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./deployment/ssl:/etc/nginx/ssl
    depends_on:
      - starseed-node
    networks:
      - starseed-network

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: starseed-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - starseed-network

volumes:
  mongodb_data:
  postgresql_data:
  weaviate_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  redis_data:

networks:
  starseed-network:
    driver: bridge 