name: kOS Vector Store CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      weaviate:
        image: semitechnologies/weaviate:latest
        ports:
          - 8080:8080
        options: >
          --health-cmd="curl -f http://localhost:8080/v1/.well-known/ready || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install fastapi uvicorn weaviate-client pydantic pytest

      - name: Run Pytest Test Suite
        run: |
          pytest tests/

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3
        with:
          dockerfile: Dockerfile

      - name: Build Docker Image
        run: |
          docker build -t kos-vector-store .

      - name: Test API Startup
        run: |
          docker run --rm -p 8000:8000 kos-vector-store uvicorn vector_store_rest:app --host 0.0.0.0 --port 8000 &
          sleep 10
          curl -f http://localhost:8000/docs

      - name: Archive Test Artifacts (Optional)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: tests/*.log
