global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vector_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['vector_api:8000']

  - job_name: 'weaviate'
    metrics_path: /v1/metrics
    static_configs:
      - targets: ['weaviate:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "alert_rules.yml"

# Note:
# Replace target hostnames with actual Docker Compose service names or IPs as needed for your environment.
