"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TabsContent = exports.TabsTrigger = exports.TabsList = exports.Tabs = exports.Input = exports.Button = void 0;
var Button_1 = require("./Button");
Object.defineProperty(exports, "Button", { enumerable: true, get: function () { return Button_1.Button; } });
var Input_1 = require("./Input");
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return Input_1.Input; } });
var Tabs_1 = require("./Tabs");
Object.defineProperty(exports, "Tabs", { enumerable: true, get: function () { return Tabs_1.Tabs; } });
Object.defineProperty(exports, "TabsList", { enumerable: true, get: function () { return Tabs_1.TabsList; } });
Object.defineProperty(exports, "TabsTrigger", { enumerable: true, get: function () { return Tabs_1.TabsTrigger; } });
Object.defineProperty(exports, "TabsContent", { enumerable: true, get: function () { return Tabs_1.TabsContent; } });
