# kOS History System Configuration

# Relative path (from repository root) to the active changelog file
default_changelog: agents/01_AGENT_CHANGELOG_LATEST.md

# Directory where quarterly archives will be stored
quarter_archive_dir: agents/01_agent_archives

# Fallback agent identifier if $AGENT_NAME is not set
default_agent: Unknown-Agent

# Directory holding template files
template_dir: agents/templates
