# kOS User Story: Content Creation Workflow

## Scenario: SEO Blog Post Generation

**User:** Alex\
**Goal:** "Write me a 1000-word SEO-friendly blog post about the benefits of decentralized AI systems."

---

## Step 1: User Input (Natural Language Command)

Alex types:

> "Write me a 1000-word SEO blog post about the benefits of decentralized AI systems."

---

## Step 2: Intent Parsing (Orchestration Layer)

- The **Orchestration Engine** parses the input.
- **Detected Intent:** `create_blog_post`
- **Parameters Extracted:**
  - Topic: `decentralized AI systems`
  - Length: `1000 words`
  - Style: `SEO-focused`

---

## Step 3: Recipe Selection

The engine queries the **Recipe Registry** and selects:

```yaml
recipe_name: generate_seo_blog_post
steps:
  - skill: keyword_research
    input: {topic}
  - skill: generate_content_outline
    input: {topic, keywords}
  - skill: expand_outline_into_article
    input: {outline}
  - skill: seo_optimize_text
    input: {draft_article, keywords}
  - skill: ethical_content_review
    input: {seo_article}
  - skill: format_for_web
    input: {final_article}
```

---

## Step 4: Skill Execution Flow

| Step | Skill                         | Node Class Responsible | Adapter Used                                                  |
| ---- | ----------------------------- | ---------------------- | ------------------------------------------------------------- |
| 1    | `keyword_research`            | GAL                    | External SEO API Adapter (e.g., SEMrush or Local TF-IDF Tool) |
| 2    | `generate_content_outline`    | Skald                  | OpenAI Adapter or Local LLM                                   |
| 3    | `expand_outline_into_article` | Skald                  | OpenAI Adapter or Local LLM                                   |
| 4    | `seo_optimize_text`           | Skald + GAL            | SEO Adapter + LLM                                             |
| 5    | `ethical_content_review`      | Junzi                  | Internal Ethics Filter                                        |
| 6    | `format_for_web`              | Skald                  | Markdown Formatter Adapter or Local Template Engine           |

---

## Step 5: Multi-Agent Collaboration

| Agent     | Role                                                    |
| --------- | ------------------------------------------------------- |
| **Skald** | Drafts, formats, and styles the content                 |
| **GAL**   | Handles keyword research and fact-checking              |
| **Junzi** | Performs ethical safety review before publication       |
| **Flux**  | Monitors skill performance and recommends optimizations |
| **Dere**  | Adjusts tone based on user preferences (optional)       |

---

## Step 6: Adapter Usage

| Adapter                                   | Purpose                        |
| ----------------------------------------- | ------------------------------ |
| **OpenAI Adapter**                        | LLM content generation         |
| **Local LLM Adapter (Ollama, LM Studio)** | Alternative LLM execution      |
| **SEO API Adapter**                       | Keyword research               |
| **Markdown Formatter Adapter**            | Formatting for blog publishing |

Adapters allow skills to remain agnostic about where or how tasks are executed.

---

## Step 7: Ethical Checkpoint (Junzi)

Before delivery:

- **Bias Check:** ✅
- **Factuality Check:** ✅
- **Toxicity Check:** ✅

If flagged, Junzi can:

- Trigger an AI Roundtable (multi-agent review)
- Escalate to user for manual approval

---

## Step 8: Output Delivery

- Final SEO-optimized, ethically-reviewed blog post is delivered to Alex.
- Stored as an **Artifact** in the **Artifact Vault**.
- Metadata tagged:
  - Topic: `AI`, `Decentralization`, `SEO`
  - Word Count: `1000`
  - Generated By: `Skald Node`, `GAL Node`, `Junzi Node`

---

## Step 9: Meta-Learning Feedback Loop (Flux)

- Alex gives a thumbs-up 👍 rating.
- **Flux Layer logs:**
  - Service latency per step
  - Total API costs
  - User satisfaction
  - Adapter performance

Future similar tasks will auto-optimize for cost, speed, and quality.

---

## ✅ Summary of kOS Workflow for Content Creation

**Natural Language Input → Intent Parsing → Recipe Selection → Skill Execution → Adapter Calls → Agent Collaboration → Ethical Filtering → Output Delivery → Meta-Learning Optimization**

---

**End of Document**

