name: Verify Docs Front-Matter

on:
  pull_request:
    paths:
      - "agents/**.md"
      - "scripts/validate_frontmatter.py"
  push:
    branches: [main]
    paths:
      - "agents/**.md"
      - "scripts/validate_frontmatter.py"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run front-matter validator
        run: python scripts/validate_frontmatter.py 